"""Native Streamlit workflow status panels."""

from __future__ import annotations

from typing import Literal

import streamlit as st

from multi_agentic_graph_rag.domain.enums import RunStatus
from multi_agentic_graph_rag.ui.presenters.workflow_presenter import (
    latest_event,
    states_table,
    status_label,
)
from multi_agentic_graph_rag.workflows.events import WorkflowRunSnapshot


def render_execution_status(run: WorkflowRunSnapshot | None) -> None:
    """Render stage states and the latest sanitized activity."""
    st.subheader("Execution status")
    if run is None:
        st.info("No request has been accepted in this session.")
        st.table(states_table(None))
        return

    event = latest_event(run)
    status_state: Literal["running", "complete", "error"] = (
        "error" if run.status in {RunStatus.BLOCKED, RunStatus.FAILED} else "complete"
    )
    with st.status(status_label(run.status), state=status_state, expanded=True):
        st.table(
            [
                {
                    "Timestamp": event.timestamp.isoformat()
                    if event
                    else run.updated_at.isoformat(),
                    "Stage": event.stage.label if event else "N/A",
                    "Activity": event.activity if event else "N/A",
                    "Attempt": event.attempt if event else 1,
                    "Item count": event.item_count if event else 0,
                    "Duration (ms)": event.duration_ms if event else 0,
                    "Error summary": event.error_summary or "None" if event else "None",
                }
            ]
        )
    st.table(states_table(run))


def render_artifact_panel(run: WorkflowRunSnapshot | None) -> None:
    """Render artifact/evidence placeholders without inventing outputs."""
    st.subheader("Artifacts, coverage, and evidence")
    if run is None:
        st.info("Artifacts will appear only after later stages generate them.")
        return
    st.table(
        [
            {
                "Run ID": str(run.request.run_id),
                "Artifacts": "Not generated by F-004",
                "Evidence": "No document content read",
                "Coverage": "Not available until Stage 3",
            }
        ]
    )
